version: "3"
services:
  user_service:
    build: .
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
volumes:
  mongo-db:
