version: "3"
services:
  product-service:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_USER=hassan
      - MONGO_PWD=word2pass
      - SESSION_SECRET=thisissecret
    # ports:
    #   - "4000:4000"
    command: npm run dev-start

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hassan
      - MONGO_INITDB_ROOT_PASSWORD=word2pass
