version: "3.4"
services:
  product-service:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGO_USER=inam
      - MONGO_PWD=word2pass
    ports:
      - "4000:4000"
    command: npm run dev-start

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=inam
      - MONGO_INITDB_ROOT_PASSWORD=word2pass
