version: "3"
services:
  product-service:
      build:
        context: .
        args:
          - NODE_ENV=production
      environment:
        - NODE_ENV=production
        - PORT=3000
      # ports:
      #   - "3000:3000"
      command: node index.js
      # env_file:
      #   - ./.env
