version: "3.4"
services:
  product-service:
    build: .
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db

networks:
  default:
    external:
      name: nginx_net

volumes:
  mongo-db:
